/**
 * Generated by PM33 Content Factory Sync
 * Source: /Users/ssaper/Desktop/my-projects/PM33/final drafts/blogs/ai-project-management-software-guide.md
 * Target keyword: Ai Project Management Software Guide
 * Generated: 2025-08-22T21:04:49.709Z
 */

'use client';

import { Container, Title, Text, Button, Card, Stack, Group } from '@mantine/core';
import Link from 'next/link';

export default function AiProjectManagementSoftwareGuidePage() {
  return (
    <div className="marketing-context">
      <Container size={1200} px={24} py={80}>
        {/* Hero Section */}
        <Card shadow="md" padding={32} radius={16} mb={48}>
          <Stack align="center" gap={24}>
            <Title order={1} size="48px" fw={700} ta="center">
              AI Project Management Software: The Complete 2025 Guide (Traditional PM vs AI-Enhanced)
            </Title>
            
            <Text size="xl" c="var(--marketing-text-secondary)" ta="center" maw={800}>
              1. Replace Everything (Traditional AI PM Platforms)
            </Text>
            
            <Group>
              <Button 
                component={Link}
                href="/trial"
                size="lg"
                style={{ 
                  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                  color: 'white',
                  fontWeight: 600
                }}
              >
                Start Free 14-Day Trial
              </Button>
              
              <Button 
                component={Link}
                href="/strategic-intelligence"
                size="lg"
                variant="outline"
                style={{ borderColor: 'var(--marketing-primary)' }}
              >
                See Live Demo
              </Button>
            </Group>
          </Stack>
        </Card>

        {/* Content would be loaded from original markdown file */}
        <Card shadow="sm" padding={32} radius={16}>
          <Text size="lg" mb="lg">
            Content from: <code>Ai Project Management Software Guide</code>
          </Text>
          <Text c="dimmed">
            This page was generated from your content factory. 
            To display full content, implement markdown processing in the component.
          </Text>
        </Card>

        {/* CTA Section */}
        <Card 
          shadow="xl" 
          padding="xl" 
          radius="lg" 
          mt={60} 
          ta="center"
          style={{
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            color: 'white'
          }}
        >
          <Title order={2} c="white" mb="lg">Ready to Transform Your PM Workflow?</Title>
          <Text size="lg" mb="lg" opacity={0.9}>
            Join 2,500+ product managers using PM33's AI-powered strategic intelligence platform
          </Text>
          <Group justify="center">
            <Button 
              size="lg"
              variant="white"
              color="dark"
              component={Link}
              href="/trial"
            >
              Start Free Trial
            </Button>
            <Button 
              size="lg"
              variant="outline"
              style={{ borderColor: 'white', color: 'white' }}
              component={Link}
              href="/strategic-intelligence"
            >
              See Live Demo
            </Button>
          </Group>
        </Card>
      </Container>
    </div>
  );
}