version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://pm33_user:pm33_password@db:5432/pm33_db
      - DATABASE_URL_SYNC=postgresql://pm33_user:pm33_password@db:5432/pm33_db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=pm33_db
      - POSTGRES_USER=pm33_user
      - POSTGRES_PASSWORD=pm33_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Database management UI
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: