'use client';

import { Container, Title, Text, Button, Card } from '@mantine/core';
import Link from 'next/link';

export default function AiPoweredProductManagement2024Page() {
  return (
    <Container size={1200} px={24} py={80}>
      <div className="marketing-context">
        {/* Auto-generated content for: AI-powered product management 2024 */}
        <Card shadow="md" padding={32} radius={16}>
          <Title order={1} size="48px" fw={700} ta="center">
            AI-powered product management 2024: The Tool That Supercharges Your Existing Stack
          </Title>
          
          <Text size="xl" c="var(--marketing-text-secondary)" ta="center" mt={24}>
            Don't replace your PM tools - make them 10x smarter with AI-powered intelligence.
          </Text>
          
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', marginTop: 32 }}>
            <Button 
              component={Link}
              href="/trial"
              size="lg"
              style={{ backgroundColor: 'var(--marketing-cta)' }}
            >
              Start Free 14-Day Trial
            </Button>
            
            <Button 
              component={Link}
              href="/strategic-intelligence"
              size="lg"
              variant="outline"
              style={{ borderColor: 'var(--marketing-primary)' }}
            >
              See Live Demo
            </Button>
          </div>
        </Card>
        
        {/* Generated by PM33 Keyword Factory */}
        {/* Target keyword: AI-powered product management 2024 */}
        {/* Generated: 2025-08-21 */}
      </div>
    </Container>
  );
}