'use client';

import { Container, Title, Text, Button, Card, Group, List, Stack, Badge, Divider } from '@mantine/core';
import { IconRocket, IconBrain, IconTarget, IconShield, IconClock, IconTrendingUp } from '@tabler/icons-react';
import Link from 'next/link';

/**
 * Sales Funnel Landing Page: AI product management tool
 * Generated by PM33 Sales Funnel Factory
 * Based on PM33 Sales Playbook strategy for maximum conversion
 * Target Audience: Finally think strategically with AI product management tool, not just tactically
 */

export default function AiproductmanagementtoolFunnelPage() {
  return (
    <Container size={1200} px={24} py={40}>
      <div className="marketing-context">
        
        {/* SALES PLAYBOOK: Opening Hook (30 seconds) */}
        <Card shadow="xl" padding={48} radius={20} mb={40} 
              style={{ 
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                color: 'white',
                textAlign: 'center'
              }}>
          <Title order={1} size="56px" fw={800} mb={24}>
            Transform from reactive AI product management tool to strategic product leadership in 10 minutes. Get complete strategic analysis that normally costs $2,000 in consulting fees.
          </Title>
          
          <Group justify="center" gap={24} mt={32}>
            <Button 
              component={Link}
              href="/trial"
              size="xl"
              radius="xl"
              style={{ 
                backgroundColor: 'var(--marketing-cta)',
                fontSize: '18px',
                padding: '16px 32px'
              }}
              leftSection={<IconRocket size={20} />}
            >
              Start Free 14-Day Trial
            </Button>
            
            <Button 
              component={Link}
              href="/strategic-intelligence"
              size="xl"
              variant="outline"
              radius="xl"
              style={{ 
                borderColor: 'white',
                color: 'white',
                fontSize: '18px',
                padding: '16px 32px'
              }}
              leftSection={<IconBrain size={20} />}
            >
              See Live Demo
            </Button>
          </Group>
        </Card>

        {/* SALES PLAYBOOK: Problem Agitation (1 minute) */}
        <Card shadow="md" padding={40} radius={16} mb={40}>
          <Title order={2} size="36px" fw={700} mb={24} ta="center">
            Let me guess what your week looks like...
          </Title>
          
          <List spacing="md" size="lg" center>
            
            <List.Item icon={<IconClock color="var(--marketing-cta)" />}>
              <Text size="lg">Monday: 3-hour AI product management tool meetings with no clear outcome</Text>
            </List.Item>
            <List.Item icon={<IconClock color="var(--marketing-cta)" />}>
              <Text size="lg">Tuesday: Scrambling to understand competitor moves</Text>
            </List.Item>
            <List.Item icon={<IconClock color="var(--marketing-cta)" />}>
              <Text size="lg">Wednesday: Arguing about resource allocation with no data</Text>
            </List.Item>
            <List.Item icon={<IconClock color="var(--marketing-cta)" />}>
              <Text size="lg">Thursday: Building another spreadsheet that'll be outdated tomorrow</Text>
            </List.Item>
            <List.Item icon={<IconClock color="var(--marketing-cta)" />}>
              <Text size="lg">Friday: Realizing you spent 40% of your week on analysis instead of building</Text>
            </List.Item>
          </List>
          
          <Text size="xl" fw={600} ta="center" mt={32} c="var(--marketing-cta)">
            Sound familiar? You're using 1990s methods to compete in 2025.
          </Text>
        </Card>

        {/* SALES PLAYBOOK: Solution Introduction */}
        <Card shadow="md" padding={40} radius={16} mb={40}>
          <Title order={2} size="36px" fw={700} mb={24} ta="center">
            PM33: Your AI Strategy Copilot
          </Title>
          
          <Text size="xl" ta="center" mb={32}>
            Think of it as having McKinsey, your best PM mentor, and a data scientist combined into one platform that thinks alongside you.
          </Text>
          
          <Badge size="xl" variant="gradient" 
                 gradient={{ from: 'blue', to: 'purple' }}
                 style={{ display: 'block', margin: '0 auto', padding: '12px 24px' }}>
            Don't just manage AI product management tool - dominate your market with strategic intelligence
          </Badge>
        </Card>

        {/* SALES PLAYBOOK: Demo Scenarios */}
        <Card shadow="md" padding={40} radius={16} mb={40}>
          <Title order={2} size="36px" fw={700} mb={32} ta="center">
            Watch PM33 in Action: Real Strategic Scenarios
          </Title>
          
          <Stack gap="lg">
            
            <Card padding="lg" radius="md" style={{ backgroundColor: 'var(--marketing-bg-secondary)' }}>
              <Group>
                <Badge color="blue" size="lg">1</Badge>
                <Text size="lg" fw={500}>Competitor raised $50M and launched competing feature - strategic response</Text>
              </Group>
            </Card>
            <Card padding="lg" radius="md" style={{ backgroundColor: 'var(--marketing-bg-secondary)' }}>
              <Group>
                <Badge color="blue" size="lg">2</Badge>
                <Text size="lg" fw={500}>$30K budget: hire junior engineer vs invest in paid marketing</Text>
              </Group>
            </Card>
            <Card padding="lg" radius="md" style={{ backgroundColor: 'var(--marketing-bg-secondary)' }}>
              <Group>
                <Badge color="blue" size="lg">3</Badge>
                <Text size="lg" fw={500}>Generate Q1 roadmap optimized for user growth with current resources</Text>
              </Group>
            </Card>
          </Stack>
          
          <Text size="lg" ta="center" mt={24} fw={600}>
            Each analysis saves you 6 hours and gives you 85% confidence vs 60%
          </Text>
        </Card>

        {/* SALES PLAYBOOK: ROI Justification */}
        <Card shadow="md" padding={40} radius={16} mb={40} 
              style={{ backgroundColor: 'var(--marketing-success)', color: 'white' }}>
          <Title order={2} size="36px" fw={700} mb={32} ta="center">
            Let's Do The Math: ROI Calculation
          </Title>
          
          <Group grow>
            <Stack align="center">
              <IconTrendingUp size={48} />
              <Text size="sm">16 hours/week on strategic analysis = 64 hours/month</Text>
            </Stack>
            <Stack align="center">
              <IconTarget size={48} />
              <Text size="sm">PM33 reduces this to 4 hours/month = 60 hours saved</Text>
            </Stack>
            <Stack align="center">
              <IconShield size={48} />
              <Text size="sm">At $100/hour PM value = $6,000 monthly value</Text>
            </Stack>
          </Group>
          
          <Divider my="lg" />
          
          <Text size="xl" ta="center" fw={800}>
            PM33 costs $29/month → 207x return on investment
          </Text>
          
          <Text size="lg" ta="center" mt={16}>
            Plus: 85% decision confidence vs 60% • Respond in hours, not weeks
          </Text>
        </Card>

        {/* SALES PLAYBOOK: Pricing */}
        <Card shadow="md" padding={40} radius={16} mb={40}>
          <Title order={2} size="36px" fw={700} mb={32} ta="center">
            Pricing That Scales with Value
          </Title>
          
          <Card padding="xl" radius="lg" 
                style={{ 
                  backgroundColor: 'var(--marketing-primary)', 
                  color: 'white',
                  textAlign: 'center'
                }}>
            <Title order={3} mb={16}>Perfect for Individual PMs</Title>
            <Text size="48px" fw={800}>$29</Text>
            <Text size="lg">/month</Text>
            <Text size="md" mt={16}>
              40 Intelligence Operations • $0.73/operation
            </Text>
          </Card>
        </Card>

        {/* SALES PLAYBOOK: Risk Reversal */}
        <Card shadow="md" padding={40} radius={16} mb={40} 
              style={{ borderLeft: '8px solid var(--marketing-success)' }}>
          <Title order={2} size="28px" fw={700} mb={24}>
            30-Day Transformation Guarantee
          </Title>
          
          <List spacing="sm">
            
            <List.Item icon={<IconShield color="var(--marketing-success)" />}>
              <Text>No credit card required for 14-day full access</Text>
            </List.Item>
            <List.Item icon={<IconShield color="var(--marketing-success)" />}>
              <Text>Keep all generated strategic documents even if you cancel</Text>
            </List.Item>
            <List.Item icon={<IconShield color="var(--marketing-success)" />}>
              <Text>Free migration assistance from current tools</Text>
            </List.Item>
            <List.Item icon={<IconShield color="var(--marketing-success)" />}>
              <Text>30-day money-back guarantee after purchase</Text>
            </List.Item>
            <List.Item icon={<IconShield color="var(--marketing-success)" />}>
              <Text>Grandfather pricing: Lock in launch rates forever</Text>
            </List.Item>
          </List>
        </Card>

        {/* SALES PLAYBOOK: Urgency Close */}
        <Card shadow="xl" padding={48} radius={20} 
              style={{ 
                background: 'linear-gradient(135deg, #EA580C 0%, #DC2626 100%)',
                color: 'white',
                textAlign: 'center'
              }}>
          <Title order={2} size="32px" fw={700} mb={24}>
            The Market Is Moving Fast
          </Title>
          
          <Text size="xl" mb={32}>
            Every day without strategic intelligence is a day your competitors pull ahead
          </Text>
          
          <Group justify="center" gap={24}>
            <Button 
              component={Link}
              href="/trial"
              size="xl"
              variant="white"
              radius="xl"
              style={{ fontSize: '20px', padding: '16px 40px' }}
            >
              Transform Now - Free Trial
            </Button>
          </Group>
          
          <Text size="sm" mt={16} opacity={0.9}>
            No credit card required • 2-minute setup • Instant value
          </Text>
        </Card>
        
        {/* Generated by PM33 Sales Funnel Factory */}
        {/* Target keyword: AI product management tool */}
        {/* Sales strategy: PM33 Sales Playbook integration */}
        {/* Generated: 2025-08-21 */}
        
      </div>
    </Container>
  );
}